language: java
jdk:
  - openjdk8
sudo: required
dist: trusty
services:
  - docker
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - DOCKER_HOST="tcp://127.0.0.1:2375"
    - MAVEN_OPTS="-XX:MaxPermSize=2g -Xmx4g -Dfile.encoding=UTF-8"
    - JAVA_OPTS="-XX:MaxPermSize=2g -Xmx4g -Dfile.encoding=UTF-8"
script:
  - java -version
  - mvn clean install -Pqulice -PdockerITs --errors --quiet -DskipITs -Dinvoker.skip=true
before_install:
  - rvm install 2.6.0
  - rvm use 2.6.0
install:
  - gem install pdd -v 0.20.5
  - gem install xcop -v 0.6
  - gem install est -v 0.3.4
